name: CI - Build & Smoke Test

on:
  push:

jobs:
  build-and-push:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push image
        uses: ./.github/actions/build-and-push
        with:
          image: ghcr.io/${{ github.repository_owner }}/github-runner
          tags: ${{ github.ref_name }}-${{ github.sha }}
          context: docker/github-runner
          dockerfile: docker/github-runner/Dockerfile
          entrypoint: entrypoint.sh
          push: false
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          platforms: linux/amd64,linux/arm64