name: Test Runners

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  test-job-1:
    runs-on: self-hosted
    steps:
      - name: Print message
        run: echo "ðŸš€ Job 1 executado no runner $RUNNER_NAME"

  test-job-2:
    runs-on: self-hosted
    steps:
      - name: Print message
        run: echo "ðŸš€ Job 2 executado no runner $RUNNER_NAME"

  test-job-3:
    runs-on: self-hosted
    steps:
      - name: Print message
        run: echo "ðŸš€ Job 3 executado no runner $RUNNER_NAME"